# =====================================
# Docker Compose - AutoMarket MultiTenant
# =====================================
# Configuración completa para desarrollo y producción

version: '3.9'

services:
  # =====================================
  # BASE DE DATOS POSTGRESQL + SUPABASE
  # =====================================
  database:
    image: postgres:16-alpine
    container_name: automarket-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-automarket}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./db/schema_optimized.sql:/docker-entrypoint-initdb.d/02_schema.sql:ro
      - ./db/migration_to_optimized.sql:/docker-entrypoint-initdb.d/03_migration.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-automarket}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - automarket-network

  # =====================================
  # REDIS PARA CACHE Y SESIONES
  # =====================================
  redis:
    image: redis:7-alpine
    container_name: automarket-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - automarket-network

  # =====================================
  # FRONTEND REACT (DESARROLLO)
  # =====================================
  frontend-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    container_name: automarket-frontend-dev
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
      - frontend_cache:/app/.vite
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_DEFAULT_TENANT=${VITE_DEFAULT_TENANT:-demo}
      - VITE_APP_TITLE=AutoMarket MultiTenant (Dev)
      - VITE_APP_VERSION=1.0.0-dev
    networks:
      - automarket-network
    profiles:
      - development

  # =====================================
  # FRONTEND REACT (PRODUCCIÓN)
  # =====================================
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_APP_TITLE=AutoMarket MultiTenant
        - VITE_APP_VERSION=1.0.0
    container_name: automarket-frontend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${FRONTEND_PORT:-80}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - automarket-network
    profiles:
      - production

  # =====================================
  # ADMINER PARA GESTIÓN DE BD
  # =====================================
  adminer:
    image: adminer:latest
    container_name: automarket-adminer
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: nette
    networks:
      - automarket-network
    profiles:
      - development
      - tools

  # =====================================
  # PGADMIN PARA GESTIÓN AVANZADA DE BD
  # =====================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: automarket-pgadmin
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@automarket.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/pgadmin_servers.json:/pgadmin4/servers.json:ro
    networks:
      - automarket-network
    profiles:
      - development
      - tools

  # =====================================
  # NGINX PROXY (PARA PRODUCCIÓN)
  # =====================================
  nginx-proxy:
    image: nginx:alpine
    container_name: automarket-proxy
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
      - "${PROXY_HTTPS_PORT:-443}:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - automarket-network
    profiles:
      - production

  # =====================================
  # MONITORING CON PROMETHEUS
  # =====================================
  prometheus:
    image: prom/prometheus:latest
    container_name: automarket-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - automarket-network
    profiles:
      - monitoring

  # =====================================
  # GRAFANA PARA VISUALIZACIÓN
  # =====================================
  grafana:
    image: grafana/grafana:latest
    container_name: automarket-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - automarket-network
    profiles:
      - monitoring

# =====================================
# VOLÚMENES PERSISTENTES
# =====================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  frontend_cache:
    driver: local
  nginx_logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# =====================================
# REDES
# =====================================
networks:
  automarket-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16