version: "3.9"
services:
  # Base de datos PostgreSQL
  db:
    image: postgres:16
    container_name: automarket_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - automarket_network

  # Adminer para administración de DB
  adminer:
    image: adminer
    container_name: automarket_adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - automarket_network
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  db_data:

networks:
  automarket_network:
    driver: bridge