name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1 — PK compuesta o índice por tenant_id (8 pts)
      id: test-1-pk-compuesta-o-indice-por-tenant_id-8-pts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 1 — PK compuesta o índice por tenant_id (8 pts)
        setup-command: 'true'
        command: bash -lc 'grep -Ei "primary key *\\( *tenant_id *, *id *\\)" db/init.sql
          || grep -Ei "create index .*\\( *tenant_id *, *id *\\)" db/init.sql && echo
          PASS || echo FAIL'
        timeout: 1
        max-score: 8
    - name: Test 2 — BD inicializa + 2 tenants (6 pts)
      id: test-2-bd-inicializa-2-tenants-6-pts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 2 — BD inicializa + 2 tenants (6 pts)
        setup-command: docker rm -f pg >/dev/null 2>&1 || true; docker run --name
          pg -e POSTGRES_DB=saas -e POSTGRES_USER=saas_user -e POSTGRES_PASSWORD=saas_pass
          -p 5432:5432 -d postgres:16; for i in {1..60}; do docker exec pg pg_isready
          -U saas_user -d saas && break; sleep 1; done; docker exec -i pg psql -U
          saas_user -d saas < db/init.sql
        command: docker exec pg psql -U saas_user -d saas -Atc "select count(*) from
          tenants;"
        timeout: 3
        max-score: 6
    - name: Test 3 — Evidencia de scoping por tenant (6 pts)
      id: test-3-evidencia-de-scoping-por-tenant-6-pts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 3 — Evidencia de scoping por tenant (6 pts)
        setup-command: 'true'
        command: bash -lc 'grep -qi "where[[:space:]]\\+tenant_id" scripts/verify_tenant.sql
          api/README.md && echo PASS || echo FAIL'
        timeout: 1
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1-PK-COMPUESTA-O-INDICE-POR-TENANT_ID-8-PTS_RESULTS: "${{steps.test-1-pk-compuesta-o-indice-por-tenant_id-8-pts.outputs.result}}"
        TEST-2-BD-INICIALIZA-2-TENANTS-6-PTS_RESULTS: "${{steps.test-2-bd-inicializa-2-tenants-6-pts.outputs.result}}"
        TEST-3-EVIDENCIA-DE-SCOPING-POR-TENANT-6-PTS_RESULTS: "${{steps.test-3-evidencia-de-scoping-por-tenant-6-pts.outputs.result}}"
      with:
        runners: test-1-pk-compuesta-o-indice-por-tenant_id-8-pts,test-2-bd-inicializa-2-tenants-6-pts,test-3-evidencia-de-scoping-por-tenant-6-pts
